---
- name: user module
  hosts: all
  become: yes

  vars_prompt:
  - name: input_password
    prompt: "Enter new password"
    private: True

  tasks:
  - name: change password
    ansible.builtin.user:
      name: itservices
      state: present
      password: "{{ input_password | password_hash('sha512') }}"