---
- name: change Hostname
  hosts: all
  become: yes
  remote_user: << User >>  
  become_method: sudo
  serial: 1  

  vars_prompt:
  - name: HOSTNAME
    prompt: Choose a Hostname
    private: False

  tasks:
  - name: set_hostname
    ansible.builtin.hostname:
      name: '{{ HOSTNAME }}' 
        msg: 'Hostname set {{ HOSTNAME }}'

